### ISSUE TITLE
PETSC ERROR in cylinderFlap by Allrun_parallel

### ISSUE THREAD

**Issue by Tianqi26** [precice/tutorials#20] opened 2019-01-25 06:31 UTC
Dear developers,

Thanks for your nice code. I successfully tried FSI tutorial of `flap_perp` using Openfoam-adapter and Calculix in both serial and parallel.

But I tried the FSI tutorial of cylinderFlap using _Allrun_parallel_. But it gives me the following error info:

[1]PETSC ERROR: ------------------------------------------------------------------------
[1]PETSC ERROR: Caught signal number 11 SEGV: Segmentation Violation, probably memory access out of range
[1]PETSC ERROR: Try option -start_in_debugger or -on_error_attach_debugger
[1]PETSC ERROR: or see http://www.mcs.anl.gov/petsc/documentation/faq.html#valgrind
[1]PETSC ERROR: or try http://valgrind.org on GNU/linux and Apple Mac OS X to find memory corruption errors
[1]PETSC ERROR: configure using --with-debugging=yes, recompile, link, and run 
[1]PETSC ERROR: to get more information on the crash.
[1]PETSC ERROR: User provided function() line 0 in  unknown file  

See details in this attached log file. 
[Fluid.log](https://github.com/precice/tutorials/files/2794860/Fluid.log)
[Solid.log](https://github.com/precice/tutorials/files/2794875/Solid.log)

Do you have any idea about this issue? 

Thanks,
Tianqi

**Comment by MakisH** [comment] 2019-01-25 07:45
Dear @Tianqi26,

this seems to be a duplicate of [this issue](https://github.com/precice/precice/issues/115#issuecomment-438406529), concerning Ubuntu 18.04. Is this the case?

Let's use [Gitter](https://gitter.im/precice/Lobby) for discussing any such problems. Often the issues are already known, or they are different than they seem (e.g. here a PETSc/Ubuntu problem, not a preCICE/tutorials problem).

Thank you for reporting this, anyhow, and happy simulating!

Best regards,
MakisH

**Comment by MakisH** [comment] 2019-01-25 07:48
Also note here that the `flap_perp` is a simpler tutorial, using just nearest-neighbor mapping, while the `cylinderFlap` is more advanced, using also the PETSc-based parallel RBF mapping.

You can always simply [change the mapping](https://github.com/precice/precice/wiki/Mapping-Configuration) to try it out, but expect higher error or instabilities. (only RBF and nearest-neighbor are supported at the moment in all the official adapters)

**Closed** 2019-01-30 14:15 UTC

**Comment by Tianqi26** [comment] 2019-02-01 04:07
Here just a comments for someone may have similar issue. 

This is how I resolve the issue:

System: Ubuntu 16.04
I recompiled and updated all related libaries as following order:
 
1. OpenMPI 1.10.2 compiled from source
2. PETSc 3.8.4 compiled from source using OpenMPI 1.10.2
3. preCICE 1.3.0
4. Calculix adapter (Jan.10.2019) compiled with preCICE 1.3.0
5. Openfoam adapter (Jan.03.2019) compield with preCICE 1.3.0

I guess my issue orginate from my outdated preCICE.
