### ISSUE TITLE
Tutorial Case: Perpendicular Flap FSI case - Coupling solids4Foam with OpenFoam using OpenFoam Adapter

### ISSUE THREAD

**Issue by raynoldtan** [precice/tutorials#292] opened 2022-09-08 13:18 UTC
- Tutorials state (last commit / release): Perpendicular Flap case inside the develop branch
- Versions of solvers and adapters used: OpenFoam V2012, Develop branch of the OpenFoam Adapter, NextRelease Branch of Solids4Foam
- preCICE version: 2.4
- Log files: 

```
[0]PETSC ERROR: ------------------------------------------------------------------------
[0]PETSC ERROR: Caught signal number 11 SEGV: Segmentation Violation, probably memory access out of range
[0]PETSC ERROR: Try option -start_in_debugger or -on_error_attach_debugger
[0]PETSC ERROR: or see https://petsc.org/release/faq/#valgrind
[0]PETSC ERROR: or try http://valgrind.org on GNU/linux and Apple MacOS to find memory corruption errors
[0]PETSC ERROR: configure using --with-debugging=yes, recompile, link, and run 
[0]PETSC ERROR: to get more information on the crash.
[0]PETSC ERROR: User provided function() at unknown file:0  
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 59.
```

Recently, I was trying to run the Perpendicular Flap FSI case on my linux workstation using openFoam v2012 as the fluid solver and solids4Foam, nextRelease branch as the solid solver. The OS used is Ubuntu 20.04 with gcc 9.4. The eigen library used is version 3.40. Precise was installed using spack with eigen@3.4.0. Solids4Foam was installed using the same eigen library. In order to ensure that is the case, I have set the environment variable as:

```bash
export EIGEN_DIR=/home/raynoldtan/spack/opt/spack/linux-ubuntu20.04-cascadelake/gcc-9.4.0/eigen-3.4.0-4k2lkyslxqecxkljs4yh6t7rcbrsvh7d/include/eigen3
```

before compiling solids4Foam. After compilation, I checked that the directory of ThirdParty inside solid4Foam folder is as:

![Screenshot 2022-09-08 at 10 44 11](https://user-images.githubusercontent.com/107682091/189130169-5b4469f3-4b3d-4c78-89b7-72ed77c128c3.png)

Despite using the same eigen library from spack which was used to install precice 2.4, there was the error above. I have run gdb debugger to check the source of the error and where it is coming. Attached is the screenshot.

![Screenshot 2022-09-08 at 11 50 06](https://user-images.githubusercontent.com/107682091/189130436-c39c5691-b9e8-487c-8c25-13d488cac254.png)

Please advise how to resolve this.

Thank you
Raynold

**Comment by MakisH** [comment] 2022-09-09 08:41
Closing as duplicate of https://github.com/precice/openfoam-adapter/issues/238 (I faced that issue as well, I don't know how to fix it, it is complicated as it involves both preCICE and solids4foam). The content you added here will now be discoverable from that issue. If you find any solution or workaround, please document there.

For support requests, please use the [preCICE forum](https://precice.discourse.group/).

**Closed by MakisH** 2022-09-09 08:41 UTC
