### ISSUE TITLE
Add CalculiX as a solid participant in flow-over-heated plate case

### ISSUE THREAD

**Issue by IshaanDesai** [precice/tutorials#157] opened 2021-03-02 11:19 UTC
Currently the `flow-over-heated-plate` case has the following combinations of solvers:
* `fluid-openfoam` and `solid-fenics`
* `fluid-openfoam` and `solid-nutils`

The combination of `fluid-openfoam` and `solid-calculix` needs to be added. To do this the CalculiX-Adapter needs to be modified (https://github.com/precice/calculix-adapter/issues/54)

**Comment by MakisH** [comment] 2021-04-12 20:38
Closing as duplicate of https://github.com/precice/tutorials/issues/103

**Closed by MakisH** 2021-04-12 20:38 UTC
Labels: duplicate
